# Form implementation generated from reading ui file 'mod_11.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget

from .StudentAppointmentPage import StudentAppointmentPage_ui 
from .StudentBrowseFacultyPage import StudentBrowseFaculty_ui
from .StudentRequestPage import StudentRequestPage_ui
from .StudentEditSchedulePage import StudentEditSchedulePage_ui

class Student_Ui_MainWindow(QWidget):
    
    def __init__(self, username, roles, primary_role, token, parent=None):
        super().__init__(parent)
        self.username = username
        self.roles = roles
        self.primary_role = primary_role
        self.token = token
        self.backIndexList = []
        self.backIndexList.append(0)
        self.currentPage = 0  # Initialize currentPage

        # Set minimum size to ensure visibility
        self.setMinimumSize(800, 600)

        self.AppointmentPage = StudentAppointmentPage_ui(self.username, self.roles, self.primary_role, self.token)
        self.AppointmentBrowseFacultyPage = StudentBrowseFaculty_ui(self.username, self.roles, self.primary_role, self.token)
        self.StudentRequestPage = StudentRequestPage_ui(self.username, self.roles, self.primary_role, self.token)
        self.StudentEditSchedulePage = StudentEditSchedulePage_ui(self.username,self.roles,self.primary_role,self.token)

        #connection

        self.AppointmentPage.go_to_AppointmentSchedulerPage.connect(self.changetoAppointmentScheduler)
        self.AppointmentPage.go_to_AppointmentReschedulePage.connect(self.changetoReschedule)
        self.AppointmentBrowseFacultyPage.go_to_RequestPage.connect(self.changetoReschedule)
        self.AppointmentBrowseFacultyPage.back.connect(self.backclicked)
        self.StudentEditSchedulePage.back.connect(self.backclicked)
        self.StudentRequestPage.back.connect(self.backclicked)

        # Initialize the UI
        self.setupUi(self)
        
        print(f"Ui_MainWindow: Initialized for user {username} with role {primary_role}")

    def setupUi(self, MainWindow):
        # Since this is used as a widget, not a main window, we don't need to set up menu/status bars
        # Just set up the central content
        self._setupCentralWidget(MainWindow)
        
        # Set initial page
        self.stackedWidget.setCurrentIndex(0)

        # Initialize simple navigation and interaction
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def _setupCentralWidget(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Main layout for central widget
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        
        # Setup all UI components
        # self._setupSidebar()
        # self._setupMainContent()
        self._setupBackButton()
        
        # Apply responsive layout
        self._setupResponsiveLayout()
        # self._configureTables()
        
        # MainWindow.setCentralWidget(self.centralwidget)
        self._setupStackedWidget()

    

    def _setupStackedWidget(self):
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("""
            QWidget#widget {
                background-color: #f1f1f3; 
                border-bottom-left-radius: 10px;
                border-bottom-right-radius: 10px;
            }
        """)

        self.content_layout = QtWidgets.QVBoxLayout(self.widget)
        self.content_layout.setContentsMargins(0, 0, 0, 0)
        self.content_layout.setSpacing(0)
        self.content_layout.setObjectName("content_layout")
        # Stacked widget container
        self.stacked_container = QtWidgets.QWidget()
        self.stacked_container.setObjectName("stacked_container")
        
        stacked_layout = QtWidgets.QVBoxLayout(self.stacked_container)
        stacked_layout.setContentsMargins(20, 10, 20, 20)
        stacked_layout.setSpacing(0)
        stacked_layout.setObjectName("stacked_layout")
        
        # Main stacked widget
        self.stackedWidget = QtWidgets.QStackedWidget()
        self.stackedWidget.setObjectName("stackedWidget")
        
        # Setup all pages
        
        
        
        
        self.stackedWidget.addWidget(self.AppointmentPage)
        self.stackedWidget.addWidget(self.AppointmentBrowseFacultyPage)
        self.stackedWidget.addWidget(self.StudentRequestPage)
        self.stackedWidget.addWidget(self.StudentEditSchedulePage)
        stacked_layout.addWidget(self.stackedWidget)
        
        # Add to main content layout
        self.content_layout.addWidget(self.stacked_container, 1)
        self.main_layout.addWidget(self.widget, 1)

    
    
    

    

    def _setupBackButton(self):
        # Back button (using QPushButton for click support)
        self.backButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton_9.setFixedSize(40, 40)
        self.backButton_9.setStyleSheet("border: none; background: transparent;")
        self.backButton_9.setIcon(QtGui.QIcon(":/assets/back_button.png"))
        self.backButton_9.setIconSize(QtCore.QSize(40, 40))
        self.backButton_9.setObjectName("backButton_9")

        # Connect back button to navigation
        self.backButton_9.clicked.connect(self.goBackPage)
    def goBackPage(self):
        if self.currentPage > 0:
            self.currentPage -= 1
            self.stackedWidget.setCurrentIndex(self.currentPage)

    def _setupResponsiveLayout(self):
        # Layouts are now properly configured in the setup methods
        pass

    
    def _setupMenuAndStatusBar(self, MainWindow):
        # Menu and status bars are not needed for widgets embedded in the router
        pass
        

    
    def changetoEditschedule(self):
        self.stackedWidget.setCurrentIndex(3)
        self.backIndexList.append(3)
        
    def changetoReschedule(self):
        self.stackedWidget.setCurrentIndex(2)
        self.backIndexList.append(2)
        

    def changetoAppointmentScheduler(self):
        self.stackedWidget.setCurrentIndex(1)
        self.backIndexList.append(1)
        
    def backclicked(self):
        if len(self.backIndexList) >1:
            self.backIndexList.pop()
        lastIndex = self.backIndexList[-1] if self.backIndexList else 0
        self.stackedWidget.setCurrentIndex(lastIndex)

import sys
from PyQt6 import QtWidgets
from PyQt6.QtWidgets import QMainWindow

# Import your main class (adjust the import path as needed)
# If your file is named Student_mainWindow.py:


def main():
    # Create the application
    app = QtWidgets.QApplication(sys.argv)
    
    # Create main window
    main_window = QMainWindow()
    main_window.setWindowTitle("Student Appointment System")
    main_window.resize(1200, 800)
    
    # Create your student UI widget
    student_ui = Student_Ui_MainWindow(
        username="john_doe",
        roles=["student"],
        primary_role="student",
        token="sample_token_123"
    )
    
    # Set up the UI in the main window
    student_ui.setupUi(main_window)
    
    # Set the student widget as central widget
    main_window.setCentralWidget(student_ui)
    
    # Show the window
    main_window.show()
    
    # Start the event loop
    sys.exit(app.exec())

if __name__ == "__main__":
    main()